server:
  port: 9527

spring:
  application:
    name: outpatien-gatway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用为服务名进行路由
      routes:
        - id: payment-toute
          uri: lb://OUTPATIENT-HALL
          predicates:
            - Path=/payment/** # 断言，路径相匹配的进行路由
          filters:
            - AddRequestHeader=X-Request-red, blue

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://soft1.aldeee.com:7001/eureka
