server:
  port: 8001

spring:
  application:
    name: outpatient-hall
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/barefoot_doctor?useUnicode=true&characterEncoding=utf-8&&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true #是否向注册中心注册自己
    fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://soft2.aldeee.com:7002/eureka,http://soft1.aldeee.com:7001/eureka
  instance:
    instance-id: hall8001
    prefer-ip-address: true
    #心跳检测与续约时间
    #开发时没置小些，保证服务关闭后注册中心能即使剔除服务
    #Eureka客户端向服务发送心跳的时间间隔，单位为秒
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 2
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.clausene.hall.entities