server:
  port: 3344

spring:
  application:
    name: outpatien-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Clausene/outpatient-config.git #GitHub上面的git仓库名字
          search-paths: #搜索目录
            - outpatient-config
      label: master #读取分支
      #启动成功后访问的路径 http://ip:3344/{label}/{application}-{profile}.yml 能访问的配置文件 就表示成功了
  rabbitmq:
    host: 192.168.1.2
    port: 5672
    username: clausene
    password: 123456
eureka:
  client:
    register-with-eureka: true #是否向注册中心注册自己
    fetch-registry: true  #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://soft1.aldeee.com:7001/eureka/

##rabbitmq相关配置,暴露bus刷新配置的端点 SpringCloud Bus动态刷新全局广播
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
