server:
  port: 8005

spring:
  application:
    name: outpatient-hall
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/barefoot_doctor?useUnicode=true&characterEncoding=utf-8&&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true #是否向注册中心注册自己
    fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://soft1.aldeee.com:7001/eureka #单机版
      #defaultZone: http://soft2.aldeee.com:7002/eureka,http://soft1.aldeee.com:7001/eureka
  instance: #显示ip 和 服务器名称
    instance-id: hall8003
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.clausene.hall.entities
management:
  endpoint:
    web:
      exposuer:
        include: "*"
